# Generated by Django 4.0.5 on 2022-07-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_checkoutaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sport Wear'), ('OW', 'Out Wear'), ('SA', 'Samsung'), ('IP', 'Ipone'), ('X', 'Xiaomi'), ('H', 'Honor')], max_length=2),
        ),
    ]
